apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: modsec-v3-apache
  name: modsec-v3-apache
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: modsec-v3-apache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: modsec-v3-apache
    spec:
      containers:
      - image: owasp/modsecurity:3.0.3-apache
        imagePullPolicy: IfNotPresent
        name: modsecurity
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30