apiVersion: v1
kind: Service
metadata:
  labels:
    app: modsec-v3-apache
  name: modsec-v3-apache-nwkpp
  namespace: default
spec:
  clusterIP: 10.27.241.157
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: modsec-v3-apache
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}